### ISSUE TITLE
RFC: selection of syntax to textually describe packages

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire-index#42]
For various reasons, it is beneficial to be able to describe projects in text files, besides Ada specifications:
- Remove the need to self-compile for in-progress packages.
- Ability to use repositories not known at compile time.
- General expectations of users of package managers
- ...

A syntax/format must be chosen. Possibilities commented in #41:
- JSON (this is a proof of concept, not intended to be kept).
- YAML (supposedly more human-friendly, structurally similar to JSON).
- GPR project files or same/extended syntax in Alire-specific file.
- ...

OPAM seems to be YAML, or something similar: https://opam.ocaml.org/doc/Manual.html#General-syntax

Rust/cargo has its own thing:
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
https://doc.rust-lang.org/cargo/reference/manifest.html

**Comment by pmderodat** [comment]
Hello! Just to complement my answer to this topic in #41:

* OPAM has its own DSL, so using a YAML parser for it does not sound like an option (even if OPAM specs parse as YAML, there seems to be a lot of post-processing to do)

* Cargo does *not* have its own thing. ;-) It’s a file format called [TOML](https://github.com/toml-lang/toml), and it is independent of Rust. In particular, you can find TOML parsers in Python, JavaScript, Perl, PHP, Rust, Haskell, … Not Ada yet, though!

As I said in #41, my take on this for now is that GPR files aren’t suited for the index, YAML is too complex, JSON is too cumbersome to write, so the best contender I have in mind is TOML. What do you think?

**Comment by Fabien-Chouteau** [comment]
I also think that TOML is the best option here: simple, documented, easy to write and read, does the job.

**Comment by mosteo** [comment]
I stand corrected about TOML :+1: 
This makes me think if we can directly use the cargo manifest format, at least the parts that are not rust-specific and make sense for Ada use cases

**Comment by pmderodat** [comment]
Syntax apart, the format I proposed in #41 already looks very similar to Cargo’s manifest format. There are minor differences, for instance the `authors` field is optional in Cargo but mandatory in my proposal. Some other concepts are quite different: since for Rust projects Cargo also acts as the builder, there are information that we currently find in GPR files. Also the dependency system is quite different: you can depend on a repository directly (not just another index entry as currently in Alire).

I expect changing too many things at once (the index format, the very shape of the database, etc.) to be hard: what about tackling one enhancement after the other? We could first switch to a first version of a textual index (e.g. TOML-based if we have consensus), and then amend the shape of the index (package attributes, dependency system, etc).

**Comment by mosteo** [comment]
Yes, I thing we have a pretty clear idea of next steps so let's do this.

**Comment by mosteo** [comment]
Implemented by alire-project/alire#60
